# Generated by Django 3.1.3 on 2020-11-10 19:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('account_number', models.AutoField(help_text='Auto generated account number. Cannot be changed!', primary_key=True, serialize=False)),
                ('pin', models.CharField(help_text='A four-digit PIN number', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,4}$', 'PIN Must be 4 Digits!', 'Invalid Input')])),
                ('address', models.TextField(help_text="User's address. Please use format ")),
                ('balance', models.IntegerField(default=0, editable=False, help_text="The account's current balance.")),
                ('phone_number', models.CharField(help_text="The account owner's phone number.", max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(auto_now=True, help_text='Date that ATM Card was Issued.')),
                ('expiry_date', models.DateField(default=datetime.datetime(2022, 11, 10, 14, 39, 53, 777759), help_text='Date upon which ATM card expires.')),
                ('card_status', models.CharField(choices=[('OP', 'Open'), ('CL', "Closed'")], default='OP', help_text='Status of ATM Card. Card can Either be Open or Closed.', max_length=6)),
                ('owner_id', models.ForeignKey(help_text='Account number of card holder.', on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
    ]
