# Generated by Django 3.1.3 on 2020-11-10 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 10, 14, 42, 18, 680829), help_text='Date upon which ATM card expires.'),
        ),
    ]
