# Generated by Django 3.1.3 on 2020-11-10 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201110_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField(auto_now=True, help_text='Date that ATM Card was Issued.')),
                ('expiry_date', models.DateField(default=datetime.datetime(2022, 11, 10, 14, 43, 39, 868739), help_text='Date upon which ATM card expires.')),
                ('card_status', models.CharField(choices=[('OP', 'Open'), ('CL', "Closed'")], default='OP', help_text='Status of ATM Card. Card can Either be Open or Closed.', max_length=6)),
                ('owner_id', models.ForeignKey(help_text='Account number of card holder.', on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
