# Generated by Django 3.1.3 on 2020-11-10 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201110_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', help_text='Status of ATM Card. Card can Either be Open or Closed.', max_length=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 10, 14, 53, 47, 929942), help_text='Date upon which ATM card expires. Defaults to two years from date of issue'),
        ),
    ]
