# Generated by Django 3.1.3 on 2020-11-11 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20201111_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP', help_text='Status of ATM Card. Card can either be Open or Closed.', max_length=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 11, 16, 25, 51, 687017), help_text='Date upon which ATM card expires. Defaults to two years from date of issue'),
        ),
        migrations.AlterField(
            model_name='card',
            name='owner_id',
            field=models.ForeignKey(help_text="Card holder's account.", on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
