# Generated by Django 3.1.3 on 2020-11-11 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201111_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 11, 16, 32, 32, 139084), help_text='Date upon which ATM card expires. Defaults to two years from date of issue'),
        ),
    ]
