# Generated by Django 3.1.3 on 2020-11-13 20:41

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_auto_20201111_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 15, 41, 23, 141051), help_text='Date upon which ATM card expires. Defaults to two years from date of issue'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.CharField(help_text='A four digit PIN number.', max_length=4, validators=[django.core.validators.RegexValidator(message='PIN number must be 4 digits.', regex='^\\d{1,10}$')])),
                ('address', models.CharField(default='None', help_text="User's address.", max_length=300)),
                ('balance', models.PositiveIntegerField(default=0, help_text="User's balance.")),
                ('phone_number', models.CharField(default=11111111111, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.OneToOneField(blank=True, help_text="The user's login name.", null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
