# Generated by Django 3.1.3 on 2020-11-14 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20201113_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATMMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text="ATM Machine's Address.", max_length=300)),
                ('machine_status', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='AC', help_text='Status of ATM Machine. Mark Active if machine is functional, otherwise mark inactive.', max_length=8)),
                ('last_refill_date', models.DateField(default=datetime.datetime(2020, 11, 14, 12, 36, 26, 692038), help_text='Date upon which machine was last serviced.')),
                ('next_refill_date', models.DateField(default=datetime.datetime(2020, 11, 28, 12, 36, 26, 692038), help_text='Date upon which machine should be serviced next. Defaults to two weeks from date of last refill, but can be changed.')),
                ('min_balance_inquiry', models.PositiveIntegerField(default=25, help_text='The minimum balance enquiry. There is usually no reason to change this.')),
                ('current_balance', models.PositiveIntegerField(default=0, help_text="Machine's current balance.")),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 14, 12, 36, 26, 691037), help_text='Date upon which ATM card expires. Defaults to two years from date of issue'),
        ),
    ]
