# Generated by Django 3.1.3 on 2020-11-14 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20201114_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmmachine',
            name='last_refill_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 14, 13, 45, 26, 553969), help_text='Date upon which machine was last serviced.'),
        ),
        migrations.AlterField(
            model_name='atmmachine',
            name='next_refill_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 28, 13, 45, 26, 553969), help_text='Date upon which machine should be serviced next. Defaults to two weeks from date of last refill, but can be changed.'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('PE', 'Pending')], default='PE', help_text='Status of ATM Card. Card can either be Open or Closed. Pending means that card has been submitted by a user, but not yet approved by an admin.', max_length=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 14, 13, 45, 26, 552968), help_text='Date upon which ATM card expires. Defaults to two years from date of issue'),
        ),
    ]
