# Generated by Django 3.1.3 on 2020-11-15 18:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0024_auto_20201114_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmmachine',
            name='last_refill_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 15, 13, 47, 43, 751873), help_text='Date upon which machine was last serviced.'),
        ),
        migrations.AlterField(
            model_name='atmmachine',
            name='next_refill_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 29, 13, 47, 43, 751873), help_text='Date upon which machine should be serviced next. Defaults to two weeks from date of last refill, but can be changed.'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 15, 13, 47, 43, 750871), help_text='Date upon which ATM card expires. Defaults to two years from date of issue'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, help_text='The date and time the transaction was performed.')),
                ('transaction_status', models.CharField(choices=[('CO', 'Completed'), ('CA', 'Closed'), ('PE', 'Pending')], default='PE', help_text='Status of transaction.', max_length=10)),
                ('response_code', models.IntegerField(choices=[(0, 0), (51, 51), (54, 54)], default=0, help_text='Transaction response codes. Refer to the following link for more information: https://www.cardaccess.com.au/bank-response-codes/')),
                ('transaction_type', models.CharField(choices=[('DE', 'Deposit'), ('WI', 'Withdrawal'), ('TR', 'TR')], default='DE', help_text='The type of transaction to be processed.', max_length=10)),
                ('card_id', models.ForeignKey(help_text='Card from which transaction was performed.', on_delete=django.db.models.deletion.CASCADE, to='user.card')),
                ('machine_id', models.ForeignKey(help_text='ATM from which transaction was performed.', on_delete=django.db.models.deletion.CASCADE, to='user.atmmachine')),
                ('transfer_id', models.ForeignKey(blank=True, default=None, help_text='User in which money is transferred to. Only used in a transfer.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
