# Generated by Django 3.1.3 on 2020-11-16 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20201115_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmmachine',
            name='last_refill_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 16, 14, 10, 59, 341148), help_text='Date upon which machine was last serviced.'),
        ),
        migrations.AlterField(
            model_name='atmmachine',
            name='next_refill_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 30, 14, 10, 59, 341148), help_text='Date upon which machine should be serviced next. Defaults to two weeks from date of last refill, but can be changed.'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 14, 10, 59, 340147), help_text='Date upon which ATM card expires. Defaults to two years from date of issue'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_id',
            field=models.ForeignKey(default=None, help_text='Card from which transaction was performed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='machine_id',
            field=models.ForeignKey(default=None, help_text='ATM from which transaction was performed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.atmmachine'),
        ),
    ]
